# Generated by Django 5.2.4 on 2025-08-07 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('deck', models.CharField(max_length=100)),
                ('cards', models.JSONField()),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='tarotdeck',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
