# Generated by Django 5.2.4 on 2025-08-09 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotapp', '0002_predictionlog_alter_tarotdeck_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uk', models.CharField(db_index=True, max_length=255)),
                ('text_ru', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tarotdeck',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='cards',
            field=models.JSONField(default=list),
        ),
    ]
